### ISSUE TITLE
Min a Max values for CC faders not taking effect

### ISSUE THREAD

**Issue by andrestelex** [mochreach/midi-surf#16]
Testing it with [Digitakt Mixer](https://midisurf.app/?page=H4sIAAAAAAAA%2F7WPvW6DMBSFXyW6M0P%2BCOA1VbdUVTtVUQYDDrHqQAV2GxXx7j20Ic7QiCx3415%2FnHO%2FlrKq3OuCREu5Sh0%2B9tI0KqBCfrzqb0Vi3gU9ZOvKGFX3oJXA6KX6ooBkXTQkttth%2ByhzQJd9S5%2FSOLWRJxKz6TQ4j7okEQ7Ts6ozVVoSMTZZ9uSOKSJEEmI6yLJUxpeuDzMfvvu9zFQO9AC8KWOuD%2BsZI1Nl%2FmQGbKNy7Y7%2FYHhDx2S9niQhnhsrrQNQOmM6QMP%2F92sOw8UySnD1mOXcZ6OVx3LOarnA1WOWC5%2BNVh7LBafl6h7Lpc9GK4%2FlktMy7r3GLPvuczZaeSxDVsslrh6zXPlstPJYrjgtE2xGLSOfjVYey4jTMo5w9Zhl7LPRymMZ37LcXXMPutBWvtvJRp9wcPcDIo4fNZYHAAA%3D)

There is no impact from min and max. It always goes from 0 to 127

**Comment by ChrisWellsWood** [comment]
Just checked the code, you're right, I forgot to plumb that in! I'll patch that tonight. Thanks for raising the issue!

**Comment by ChrisWellsWood** [comment]
Hi @andrestelex, I've fixed that bug, the min and max values will take affect now. The app should be v0.3.2 on the info page. You can even set the minimum less than the maximum and it flips the behaviour of the fader (0% is max value, 100% is min). I'm closing this issue now, but let me know if you have any problems and I can reopen. Thanks for taking the time to report the bug.
