### ISSUE TITLE
Add SysEx support

### ISSUE THREAD

**Issue by narrsam** [mochreach/midi-surf#20]
I couldn't find a way to add custom sysex messages. This is a must in my opinion.

**Comment by ChrisWellsWood** [comment]
I took a look at the source, and I had SysEx at some point, but it's been commented out:
```elm
type EditMidiButtonMsg
    = ENoteOn { channel : String, pitch : String, velocity : String }
    | ENoteOff { channel : String, pitch : String, velocity : String }
    | EControllerChange { channel : String, controller : String, value : String }
    | EProgramChange { channel : String, preset : String }
    | ESongSelect String
      -- Some message types are commented out as they seem to break web midi
      -- | EUnofficialBusSelect String
    | ETuneRequest
      -- | EEndOfSysEx
      -- | ETimingTick
    | EStartSong
    | EContinueSong
    | EStopSong
    | EActiveSensing
    | ESystemReset
```
As I don't use SysEx, I didn't look into it further, but it's probably fixable. I'll take a look at it when I get time.

**Comment by ChrisWellsWood** [comment]
@narrsam this was added in a recent update: https://github.com/mochreach/midi-surf/releases/tag/v0.5.0. You can add a "command" and send SysEx messages on press or release. If you try it out, please let me know if you have any problems.

**Comment by jonnyhotchkiss** [comment]
This is such a cool app, not really anything even comes close, and the shareability feature is superb ⭐⭐⭐⭐⭐

Am trying to test sysex with jdxi, including requests to receive values. Is this currently possible, or is development required? I think it's hexadecimal that's returned.

**Comment by ChrisWellsWood** [comment]
@jonnyhotchkiss so glad you're liking the app! I think that the "MIDI Log" controller should print the sysex messages that are coming in, but it's not in the most useful format, I think the hex will be printed as a list of base 10 integers:

```elm
SystemExclusive data ->
            "System Exclusive: "
                ++ (Array.map String.fromInt data |> Array.toList |> String.join " ")
```

This can be converted back to hex relatively easily, but could be a bit of a pain. What are you wanting to do with the received sys ex? Are you wanting to store it to a file?
