### ISSUE TITLE
How to install on android?

### ISSUE THREAD

**Issue by dreadylocks** [mochreach/midi-surf#23]
What's the recommended workflow to actually install as a PWA on android? I'm trying to make it happen with cordova but it's not super straightforward. Do you have a process you're using to get an apk?

**Comment by ChrisWellsWood** [comment]
Hi @codelocksdev, when you visit MIDI Surf on your browser, you should have an option to "install as an app". You might be prompted when you first visit midisurf.app or you might have to go into a menu or there might even be a little icon somewhere like this: 
![image](https://github.com/mochreach/midi-surf/assets/8362681/c7aca662-9ba9-43e1-a408-b7a034b2dbd3)
You'll then be prompted to place the icon on your home screen.
