### ISSUE TITLE
What is exported json file for?

### ISSUE THREAD

**Issue by andybeta** [mochreach/midi-surf#24]
Hi, great idea, great app! I'm making a preset for the Roland S-1
I'd love to be able to export the json file and edit by hand using vim or textpad to add similar instances of commands. How can I import an edited json file? Thanks.

**Comment by ChrisWellsWood** [comment]
> Hi, great idea, great app! I'm making a preset for the Roland S-1
> I'd love to be able to export the json file and edit by hand using vim or textpad to add similar instances of commands. How can I import an edited json file? Thanks.

Hi @andybeta, if you add a new page, then there's an option up "import". Just load up the JSON file there and so long as it's in the correct format, it should work. Let me know how you get on with it, I haven't used that feature in ages!

**Comment by andybeta** [comment]
That's great thanks.

Here are my presets for Roland S-1. First is just effects, oscillator, filter etc.
In the second I added an isometric kb, which makes it a bit crowded but is good fun.

[Roland S-1](https://midisurf.app/?page=H4sIAAAAAAAA%2F82cTW%2FbOBCG%2F0qgs40N9WEnue2m2D1lESSH3SLIgbFpxygttfponRr5733JSKas2C4LUZweDGQ0Yw6fcTR%2BJ6azDWZZulgtg6ttMBdPFX5YcFmIUbDkn%2B9X30VwFb6OVFCZZ1KKXAWWHGHBTTavpAhGAc%2BXRXD1ENxlkqfzs%2FsxC0ZNkFpifp3Jap2ayIcH9osBd9m3w97rbL1GUuPcBll6J6Tghbgp9JXHES7d5qIo6gvNc2%2FzbJnz9fUzT5ctjm3wGcGiDK7OAQ5nKqSqwuMrVpplMqtaRfgnF6K18UfUSvInIdWuTdT9mkt5IAouNj5HuYKi5GUFX1pJqTP5YmRggnNoxhAeMsYQTHAOzRjBQ8YYgQnOoRljeMgYYzDBOTRjAg8ZYwImOIdmnMBDxjgBE5xDM07hIWOcggnOoRkv4CFjvAATnEMzXsJDxngJJjgHZmTn8JAxMj9Ch9EKHT9Kh5EqHeZH6jBSqcP8aB1GqnWYH7HDSMUO86N22CG184hHG1StRzRnMgtB9JesWs%2Fd8aldm6ATVQip50wLQeSAkbb7WggiB4y0zddCEDlgJO29oYUecsBI2npDCznkgPFQ5%2FXHaKGGHDCSzpmhhRhywEg6Z4YWWsgBI%2BmcGVpIof6MtHNm6EXn0I6ZoRedQztlhl50Du2QGXrRObQzZuRF59COmJEXnfO7T5iRhRL6KKRsb25HqPZtwk7UISKeMSMLLeSEkrT7RhZqyAklaf%2BNLPSQE0raDmyhiJxQ0vZgC03khPJQF%2FZHaaGKnFCSzpuRhS5yQkk6ccYWysgJJenMGVtoIxeUtFNn7En70M6dsSftQzt5xp60D%2B3sGXvSPrTTZ%2BxJ%2B9DOn7En7fO7T6CxhTq6E63kOzy1aRNzoggx8fgZW0ij%2Foik%2FTex0EX9EUmbb2IhivojknbexEIR9UckbbuJhRzqj3io5%2FpDtNBC%2FRFJh83EQgj1RySdNBMLFdQfkXTMTCwkUG9E2hkz8aFuaAfMxIe6oZ0uJz7UDe1oOfGhbmjnyokPdUM7VE58qJujE6V6jB6iHapa88BXOMP9gM7Yabz%2Ff%2Fybz%2FHF0p1zG3zl%2BET2hm9CnDdUByre7FUKG7eotm5FPhNpiSsTJRJm%2F1brJ5HDbB2kgdUkuX5Wt12dQHHqRZCCdVLA7qTAlamqd50CZusAOqyjKbqvyH%2FPq7L1cqoQXW1VHhN14jXZjOUiO8uK2dkfZy%2F658VKlojtvkojh%2BXVf8Co2WFOTQOB1SR5x64XQQrUZy8F7E4KXNGfnNQpYE6NsIV1NEW3vD1%2F4TfjRS6%2B6MriLssQ5LGqrROnsJok75D1IkiBsuylgI0FtFWnwBX9blangNk6uAvraIpuVfuejdiMiy8Vz4UubMFVDxiyrnp6r6FhXirzDRpWk%2BQdtF4EKVCYvRSwOylwRZ8yqFPAvDRvN7COpujWtffXGjbjuZD8Rdc1F19F%2FoS4bmnfWrV5V1Krdzux8R4tfacs76oC%2FzkuNVXBLaxq9FYUA%2FPTmnzg%2BSfU5WU%2FSgOrjZvAE2X5syz57BN83VK0y%2BAQ1LzbmO15Af0gZlwtMBCnvnN2mHsnxZrVvWDeVwDEDgcDvVAD%2BA50au5msz0voLU2hLMLqm7i5tF%2Bgvl3G68%2FAHd2TofHQwAA)

[Roland S-1 with iso kb](https://midisurf.app/?page=H4sIAAAAAAAA%2F%2B1c207jSBD9FeRnoo0d58bbLqPdl2WE4GF3hHgwoYEIEzOOMwuL%2BPc53ROnOyYhHV%2B6ylIeIrldla5zyuXuU2DnzZsks7vpvXfy5t2KmwUO7qJ4Lo69%2B%2Bj5cvq%2F8E6C92PplKVJHItUOmYR3Dxpvb1I%2FvOOvSi9n3snV1dX%2FnFuPUtuF7HQNu8iiaPZ7dFlx%2FdWTmqK0yRePM20pzmLncNWEKfJ0xOCauObl8wuRCyiuTibqzPXxzh1nor5fHki%2F%2B55mtyn0dPpQzS7N3i8ec9wFpl30kVaYJyJWObo%2Bh0zTZI4WRgp%2BisVwgB%2BjUzG0Y2IJWrtdfkUxfEGL5j8Thfp8uZZlC1gmy3iWEVyxdEHJxib5hjAQsYxACcYm%2BbYg4WMYw%2BcYGyaYwgLGccQnGBsmmMfFjKOfXCCsWmOA1jIOA7ACcamOQ5hIeM4BCcYm%2BY4goWM4wicYGya4xgWMo5jcIKxYY5%2BFxYyjr4boePTCh03SscnVTq%2BG6njk0od343W8Um1ju9G7PikYsd3o3b8TWrnGh%2BTqJyPqM%2F0LQTRH%2FHC%2BO6Kn0StnT7JQkDdZ1oIoho40q6%2BFoKoBo60i6%2BFIKqBI%2BnaG1jooRo4ki69gYUcqoHjppXXHUcLNVQDR9I%2BM7AQQzVwJO0zAwstVANH0j4zsJBC1TnS9pmBE51D22YGTnQObZcZONE5tE1m4ETn0PaYPSc6h7bF7DnROdw7zJ6FEvom4tgEt2IocWu3T%2FLQI%2B4xexZaqBaWpKtvz0IN1cKSdP3tWeihWljSrsAWiqgWlrRrsIUmqoXlplXYHUsLVVQLS9J%2Bs2ehi2phSdpxhhbKqBaWpD1naKGN6mBJ23WGjrQPbd8ZOtI%2BtJ1n6Ej70PaeoSPtQ9t9ho60D23%2FGTrSPtw70NBCHV0II%2FiKngStfT5JQkjcfoYW0qg6RdL1t2%2Bhi6pTJF18%2BxaiqDpF0pW3b6GIqlMkXXb7FnKoOsVNa647ihZaqDpF0mazbyGEqlMk7TT7FiqoOkXSNrNvIYEqU6TtMfsu1A1tg9l3oW5ou8uBC3VD21oOXKgb2r5y4ELd0DaVAxfqZmtHKT%2FHV8GKqpxzwyucBYdC26mt%2F377M7rFa6cr45v3I8J%2FZM%2BilwDPG8oHKn6NpzOMcYuq0blIJ2KW4YzqLCdfF083IsXQeJAGozzI6YO87ZYBJE81CUL4hRAYF0LgjPrT%2FjIEhsYD6BhtDVG8Iv88TDPjckoXlW2ZHu31yTV56cR3yVEynxz9dvSqju%2BmcQbf4lUyr07l9EqBsuSO4VAvIBjlQT5wV5MgBPKzFgLjQgicUX%2BHXobAcKiFLUZbQxTTW7HgXzp3qfiuMou7LIFTo1nFqZwyhsYTpxjlQT5QVpMgBNKyFgJjTKBGyxA4Y4bA0HhwF6OtIYpZrfpsxEtn%2Fn0RpUIldh7JNcBhXseysn6RxigP8oG0mgQhkJi1EBhjPjVahsAZ9ZT3MgSGY73dYLQ1RDGvlV9reOncijh6VXlNxQ%2BR3sCvmNqNS3VhJdZ71tbUg7SZlg9ZUSfynOAG1uujprIzI1%2Bi9BFZeV33UnQlbO34SVJ%2Bz7Jo8ghbMRHm1lwbTb3TaHBOaH4Rk0hO4ILl2kNi%2BeROWF4uwA8A3fAc6vtYo3PCc6kKYSzylLdv%2FllnLSffoLkKDlvv9K%2BJqUSQMxEnk2n2uszZ8zSbPOB47aWd%2FLs7c%2FL39P4hq5oUnC1mw%2BRvS0Cu1XsTqOOi4mwd%2BPWmraPuxM%2FoAhjCRkfdSaCq6MDZOrBr8aCj7sTOp3jWXn%2FJv7sTP6fiIdMROFsHft3I6Kg78Td1AeQmYpKQc1XfIdpeY0Yvr6O2ikCpIuNzk6y9A55%2Fdyd%2BThdA%2FoFkbwKMLgCO98fP6QIcRJ52U9CqEGhkm%2BjimA9Fk54tgVI1xkPHdkvVF6P7o1QPwah41n56KP%2FuTgKMLsBB5BluCpprApxEXjM7RKkaa4ihyc4Wf9tLrMupxMrgb3sf0W15H3HQeEsPhco1dk4ar4kNYoxDNgRNcpbwS9UWn5tjzKm%2B9ofvd9veQ3RL9RCcCBwEnnZT0FwT4CTwGtki2l1h45YX2JhTfZWA3%2FL%2BYVyqfWChXg%2FaTrspZI7xc9J2TWwMIxyyIWiSs4Tf8voalaovPvjHpXoHNuVjPAOtg%2B6Ezyj9B1m3clPIHOPnJOsa2R3aXV%2BjltfXqFR9sdCto1ItA5%2FKKdUxMKocHO6Pn0%2F6D7JOuylkVfA3sTMMcciHocnOEn%2BpCmNzgwxZFdj%2B%2BEft7htGLe8bDrpOuylkjvFz0XWN7AylaqsBciYxS%2Bil6orNbWH8OIAOuhM%2Bn9uC7qVhnK0Bfst7hoOk014KmGP4rCRdEzvDAId8GJrsLPG3u8AGrApsf%2FzDdvcMxq8D6aA74TNK%2F0HXSS8FzDF8VrqukZ2hVG01xdBkZ4m%2F3QU2YFVgJfCXahwY4S%2FVOfApHxzuD59R%2Bg%2B6buWmkFXBL7eH5Uf7XSQxfvDz6LLjHz2K17n3%2FhNcLssDeo0AAA%3D%3D)

Hopefully some of your users might find these useful.

Andy
